import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../lib/supabaseClient';

// ==========================================
// TYPES AND INTERFACES
// ==========================================

export type BirdType = 'Broiler' | 'Layer';
export type BatchStatus = 'Active' | 'Sold';

export interface MortalityLog {
  id: string;
  date: string;
  quantity: number;
  reason: string;
}

export interface BirdBatch {
  id: string;
  type: BirdType;
  arrivalDate: string;
  initialQuantity: number;
  currentQuantity: number;
  purchasePrice: number; // price per bird
  status: BatchStatus;
  mortalityLogs: MortalityLog[];
}

export type FeedType = 'Starter' | 'Grower' | 'Finisher' | 'Layer Mash';

export interface FeedPurchase {
  id: string;
  date: string;
  feedType: FeedType;
  quantityKg: number;
  cost: number;
  vendor: string;
}

export interface FeedConsumption {
  id: string;
  date: string;
  feedType: FeedType;
  batchId: string;
  quantityKg: number;
}

export type VaccineStatus = 'Pending' | 'Completed';

export interface VaccineSchedule {
  id: string;
  vaccineName: string;
  batchId: string;
  scheduledDate: string;
  status: VaccineStatus;
}

export interface MedicalRecord {
  id: string;
  date: string;
  batchId: string;
  disease: string;
  medicine: string;
  dosage: string;
  cost: number;
}

export interface EggCollection {
  date: string;
  collectedQty: number;
  damagedQty: number;
  netQty: number;
}

export type SaleType = 'Bird' | 'Egg';

export interface Sale {
  id: string;
  invoiceId: string;
  type: SaleType;
  date: string;
  customerName: string;
  customerContact: string;
  quantity: number; // number of birds or crates (30 eggs/crate)
  unitPrice: number;
  totalAmount: number;
  batchId?: string; // If bird sale
  details?: string;
}

export type ExpenseCategory = 'Feed' | 'Medicine' | 'Electricity' | 'Labor' | 'Water' | 'Other';

export interface Expense {
  id: string;
  category: ExpenseCategory;
  date: string;
  description: string;
  amount: number;
  isAutoGenerated: boolean;
  referenceId?: string; // ID of feed purchase or medical record
}

export type UserRole = 'Admin' | 'Employee';

export interface User {
  username: string;
  role: UserRole;
}

interface FarmContextType {
  currentUser: User | null;
  login: (username: string, role: UserRole) => boolean;
  logout: () => void;
  batches: BirdBatch[];
  addBatch: (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => void;
  deleteBatch: (batchId: string) => void;
  sellBatch: (batchId: string, quantity: number, pricePerBird: number, customerName: string, customerContact: string) => void;
  logMortality: (batchId: string, quantity: number, reason: string, date: string) => void;
  feedPurchases: FeedPurchase[];
  addFeedPurchase: (purchase: Omit<FeedPurchase, 'id'>) => void;
  feedConsumption: FeedConsumption[];
  addFeedConsumption: (consumption: Omit<FeedConsumption, 'id'>) => void;
  vaccines: VaccineSchedule[];
  addVaccineSchedule: (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => void;
  updateVaccineStatus: (id: string, status: VaccineStatus) => void;
  deleteVaccineSchedule: (id: string) => void;
  medicalRecords: MedicalRecord[];
  addMedicalRecord: (record: Omit<MedicalRecord, 'id'>) => void;
  eggCollections: EggCollection[];
  addEggCollection: (collection: EggCollection) => void;
  deleteEggCollection: (date: string) => void;
  sales: Sale[];
  addEggSale: (sale: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => void;
  deleteSale: (saleId: string) => Promise<void>;
  expenses: Expense[];
  addExpense: (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => void;
  deleteExpense: (id: string) => void;
  getFeedStock: (type: FeedType) => number;
  isLoading: boolean;
}

// ==========================================
// CONTEXT CREATION & PROVIDER
// ==========================================

const FarmContext = createContext<FarmContextType | undefined>(undefined);

export const FarmProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Session User (Kept in LocalStorage for dev auth simplicity)
  const [currentUser, setCurrentUser] = useState<User | null>(() => {
    const saved = localStorage.getItem('poultry_user');
    return saved ? JSON.parse(saved) : null;
  });

  // Core Farm States
  const [batches, setBatches] = useState<BirdBatch[]>([]);
  const [feedPurchases, setFeedPurchases] = useState<FeedPurchase[]>([]);
  const [feedConsumption, setFeedConsumption] = useState<FeedConsumption[]>([]);
  const [vaccines, setVaccines] = useState<VaccineSchedule[]>([]);
  const [medicalRecords, setMedicalRecords] = useState<MedicalRecord[]>([]);
  const [eggCollections, setEggCollections] = useState<EggCollection[]>([]);
  const [sales, setSales] = useState<Sale[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // ----------------------------------------------------
  // FETCH ALL DATA FROM SUPABASE
  // ----------------------------------------------------
  const fetchAllData = async () => {
    try {
      const [
        { data: batchesData, error: batchesErr },
        { data: mortalityData, error: mortalityErr },
        { data: feedPurchasesData, error: fpErr },
        { data: feedConsumptionData, error: fcErr },
        { data: vaccinesData, error: vErr },
        { data: medicalRecordsData, error: mrErr },
        { data: eggCollectionsData, error: ecErr },
        { data: salesData, error: sErr },
        { data: expensesData, error: expErr }
      ] = await Promise.all([
        supabase.from('batches').select('*'),
        supabase.from('mortality_logs').select('*'),
        supabase.from('feed_purchases').select('*'),
        supabase.from('feed_consumptions').select('*'),
        supabase.from('vaccine_schedules').select('*'),
        supabase.from('medical_records').select('*'),
        supabase.from('egg_collections').select('*'),
        supabase.from('sales').select('*'),
        supabase.from('expenses').select('*')
      ]);

      if (batchesErr || mortalityErr || fpErr || fcErr || vErr || mrErr || ecErr || sErr || expErr) {
        console.error('Error fetching data from Supabase:', {
          batchesErr, mortalityErr, fpErr, fcErr, vErr, mrErr, ecErr, sErr, expErr
        });
        return;
      }

      // Map Batches and their Mortality Logs
      const formattedBatches = (batchesData || []).map((b: any) => ({
        id: b.id,
        type: b.type as BirdType,
        arrivalDate: b.arrival_date,
        initialQuantity: b.initial_quantity,
        currentQuantity: b.current_quantity,
        purchasePrice: Number(b.purchase_price),
        status: b.status as BatchStatus,
        mortalityLogs: (mortalityData || [])
          .filter((m: any) => m.batch_id === b.id)
          .map((m: any) => ({
            id: m.id,
            date: m.date,
            quantity: m.quantity,
            reason: m.reason
          }))
      }));
      setBatches(formattedBatches);

      // Map Feed Purchases
      setFeedPurchases((feedPurchasesData || []).map((p: any) => ({
        id: p.id,
        date: p.date,
        feedType: p.feed_type as FeedType,
        quantityKg: Number(p.quantity_kg),
        cost: Number(p.cost),
        vendor: p.vendor
      })));

      // Map Feed Consumptions
      setFeedConsumption((feedConsumptionData || []).map((c: any) => ({
        id: c.id,
        date: c.date,
        feedType: c.feed_type as FeedType,
        batchId: c.batch_id,
        quantityKg: Number(c.quantity_kg)
      })));

      // Map Vaccine Schedules
      setVaccines((vaccinesData || []).map((v: any) => ({
        id: v.id,
        vaccineName: v.vaccine_name,
        batchId: v.batch_id,
        scheduledDate: v.scheduled_date,
        status: v.status as VaccineStatus
      })));

      // Map Medical Records
      setMedicalRecords((medicalRecordsData || []).map((m: any) => ({
        id: m.id,
        date: m.date,
        batchId: m.batch_id,
        disease: m.disease,
        medicine: m.medicine,
        dosage: m.dosage,
        cost: Number(m.cost)
      })));

      // Map Egg Collections
      setEggCollections((eggCollectionsData || []).map((e: any) => ({
        date: e.date,
        collectedQty: e.collected_qty,
        damagedQty: e.damaged_qty,
        netQty: e.net_qty
      })));

      // Map Sales
      setSales((salesData || []).map((s: any) => ({
        id: s.id,
        invoiceId: s.invoice_id,
        type: s.type as SaleType,
        date: s.date,
        customerName: s.customer_name,
        customerContact: s.customer_contact,
        quantity: Number(s.quantity),
        unitPrice: Number(s.unit_price),
        totalAmount: Number(s.total_amount),
        batchId: s.batch_id || undefined,
        details: s.details || undefined
      })));

      // Map Expenses
      setExpenses((expensesData || []).map((ex: any) => ({
        id: ex.id,
        category: ex.category as ExpenseCategory,
        date: ex.date,
        description: ex.description,
        amount: Number(ex.amount),
        isAutoGenerated: ex.is_auto_generated,
        referenceId: ex.reference_id || undefined
      })));

    } catch (err) {
      console.error('Unexpected error loading farm data:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Sync session user
  useEffect(() => {
    localStorage.setItem('poultry_user', currentUser ? JSON.stringify(currentUser) : '');
  }, [currentUser]);

  // Load initial data and subscribe to realtime updates
  useEffect(() => {
    fetchAllData();

    // Subscribe to schema changes across all public tables
    const channel = supabase
      .channel('realtime-farm-updates')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public' },
        () => {
          // Trigger a clean refetch when any database write occurs
          fetchAllData();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  // ==========================================
  // UTILITIES & STATE MUTATORS
  // ==========================================

  // Authentication (Local Session storage)
  const login = (username: string, role: UserRole): boolean => {
    if (
      (role === 'Admin' && username.toLowerCase() === 'admin') ||
      (role === 'Employee' && username.toLowerCase() === 'employee')
    ) {
      setCurrentUser({ username, role });
      return true;
    }
    return false;
  };

  const logout = () => {
    setCurrentUser(null);
  };

  // 1. Bird Management
  const addBatch = async (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => {
    const newBatch = {
      id: batch.id,
      type: batch.type,
      arrival_date: batch.arrivalDate,
      initial_quantity: batch.initialQuantity,
      current_quantity: batch.initialQuantity,
      purchase_price: batch.purchasePrice,
      status: 'Active'
    };

    const cost = batch.initialQuantity * batch.purchasePrice;
    const newExpense = {
      id: `exp-${Date.now()}`,
      category: 'Other',
      date: batch.arrivalDate,
      description: `Bird Batch Purchase: ${batch.type} - ${batch.initialQuantity} birds (ID: ${batch.id})`,
      amount: cost,
      is_auto_generated: true,
      reference_id: batch.id
    };

    // Insert to DB (realtime updates state reactively)
    await Promise.all([
      supabase.from('batches').insert(newBatch),
      supabase.from('expenses').insert(newExpense)
    ]);
  };

  const sellBatch = async (
    batchId: string,
    quantity: number,
    pricePerBird: number,
    customerName: string,
    customerContact: string
  ) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (!batch) return;

      const newCurrentQty = Math.max(0, batch.current_quantity - quantity);
      const newStatus = newCurrentQty === 0 ? 'Sold' : 'Active';

      const saleId = `s-${Date.now()}`;
      const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
      const newSale = {
        id: saleId,
        invoice_id: invoiceNum,
        type: 'Bird',
        date: new Date().toISOString().split('T')[0],
        customer_name: customerName,
        customer_contact: customerContact,
        quantity,
        unit_price: pricePerBird,
        total_amount: quantity * pricePerBird,
        batch_id: batchId,
        details: `Sold ${quantity} birds from Batch ${batchId}`
      };

      await Promise.all([
        supabase
          .from('batches')
          .update({ current_quantity: newCurrentQty, status: newStatus })
          .eq('id', batchId),
        supabase.from('sales').insert(newSale)
      ]);
    } catch (err) {
      console.error('Failed to sell batch:', err);
    }
  };

  const logMortality = async (batchId: string, quantity: number, reason: string, date: string) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (!batch) return;

      const actualQty = Math.min(batch.current_quantity, quantity);
      const newCurrentQty = batch.current_quantity - actualQty;

      const newLog = {
        id: `m-${Date.now()}`,
        batch_id: batchId,
        date,
        quantity: actualQty,
        reason
      };

      await Promise.all([
        supabase
          .from('batches')
          .update({ current_quantity: newCurrentQty })
          .eq('id', batchId),
        supabase.from('mortality_logs').insert(newLog)
      ]);
    } catch (err) {
      console.error('Failed to log mortality:', err);
    }
  };

  const deleteBatch = async (batchId: string) => {
    try {
      // Step 1: Get medical record IDs for this batch so we can delete their linked expenses
      const { data: medRecords } = await supabase
        .from('medical_records')
        .select('id')
        .eq('batch_id', batchId);

      // Step 2: Delete expenses auto-linked to medical records
      if (medRecords && medRecords.length > 0) {
        const medIds = medRecords.map((m: any) => m.id);
        await supabase
          .from('expenses')
          .delete()
          .in('reference_id', medIds)
          .eq('is_auto_generated', true);
      }

      // Step 3: Delete medical records for this batch
      await supabase.from('medical_records').delete().eq('batch_id', batchId);

      // Step 4: Delete vaccine schedules for this batch
      await supabase.from('vaccine_schedules').delete().eq('batch_id', batchId);

      // Step 5: Delete feed consumptions for this batch
      await supabase.from('feed_consumptions').delete().eq('batch_id', batchId);

      // Step 6: Delete mortality logs for this batch
      await supabase.from('mortality_logs').delete().eq('batch_id', batchId);

      // Step 7: Delete the auto-generated batch purchase expense
      await supabase
        .from('expenses')
        .delete()
        .eq('reference_id', batchId)
        .eq('is_auto_generated', true);

      // Step 8: Null out batch_id on any sales (preserve financial history)
      await supabase
        .from('sales')
        .update({ batch_id: null })
        .eq('batch_id', batchId);

      // Step 9: Finally delete the batch itself
      const { error } = await supabase.from('batches').delete().eq('id', batchId);
      if (error) throw error;

    } catch (err: any) {
      console.error('Failed to delete batch:', err);
      alert(`Delete failed: ${err?.message ?? 'Unknown error. Check console for details.'}`);
    }
  };


  const addFeedPurchase = async (purchase: Omit<FeedPurchase, 'id'>) => {
    const id = `fp-${Date.now()}`;
    const newPurchase = {
      id,
      date: purchase.date,
      feed_type: purchase.feedType,
      quantity_kg: purchase.quantityKg,
      cost: purchase.cost,
      vendor: purchase.vendor
    };

    const newExpense = {
      id: `exp-${Date.now()}`,
      category: 'Feed',
      date: purchase.date,
      description: `Feed Purchase: ${purchase.feedType} (${purchase.quantityKg} kg) from ${purchase.vendor}`,
      amount: purchase.cost,
      is_auto_generated: true,
      reference_id: id
    };

    await Promise.all([
      supabase.from('feed_purchases').insert(newPurchase),
      supabase.from('expenses').insert(newExpense)
    ]);
  };

  const addFeedConsumption = async (consumption: Omit<FeedConsumption, 'id'>) => {
    const id = `fc-${Date.now()}`;
    const newConsumption = {
      id,
      date: consumption.date,
      feed_type: consumption.feedType,
      batch_id: consumption.batchId,
      quantity_kg: consumption.quantityKg
    };
    await supabase.from('feed_consumptions').insert(newConsumption);
  };

  const getFeedStock = (type: FeedType): number => {
    const totalPurchased = feedPurchases
      .filter(p => p.feedType === type)
      .reduce((sum, p) => sum + p.quantityKg, 0);

    const totalConsumed = feedConsumption
      .filter(c => c.feedType === type)
      .reduce((sum, c) => sum + c.quantityKg, 0);

    return Math.max(0, totalPurchased - totalConsumed);
  };

  // 3. Health & Vaccination
  const addVaccineSchedule = async (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => {
    const newSchedule = {
      id: `v-${Date.now()}`,
      vaccine_name: schedule.vaccineName,
      batch_id: schedule.batchId,
      scheduled_date: schedule.scheduledDate,
      status: 'Pending'
    };
    await supabase.from('vaccine_schedules').insert(newSchedule);
  };

  const updateVaccineStatus = async (id: string, status: VaccineStatus) => {
    await supabase
      .from('vaccine_schedules')
      .update({ status })
      .eq('id', id);
  };

  const deleteVaccineSchedule = async (id: string) => {
    try {
      await supabase.from('vaccine_schedules').delete().eq('id', id);
    } catch (err) {
      console.error('Failed to delete vaccine schedule:', err);
    }
  };

  const addMedicalRecord = async (record: Omit<MedicalRecord, 'id'>) => {
    const id = `mr-${Date.now()}`;
    const newRecord = {
      id,
      date: record.date,
      batch_id: record.batchId,
      disease: record.disease,
      medicine: record.medicine,
      dosage: record.dosage,
      cost: record.cost
    };

    const operations: any[] = [supabase.from('medical_records').insert(newRecord)];

    if (record.cost > 0) {
      const newExpense = {
        id: `exp-${Date.now()}`,
        category: 'Medicine',
        date: record.date,
        description: `Medical Treatment: Batch ${record.batchId} treated for ${record.disease} (${record.medicine})`,
        amount: record.cost,
        is_auto_generated: true,
        reference_id: id
      };
      operations.push(supabase.from('expenses').insert(newExpense));
    }

    await Promise.all(operations);
  };

  // 4. Egg Production
  const addEggCollection = async (collection: EggCollection) => {
    const newCollection = {
      date: collection.date,
      collected_qty: collection.collectedQty,
      damaged_qty: collection.damagedQty,
      net_qty: collection.netQty
    };
    await supabase.from('egg_collections').upsert(newCollection);
  };

  const deleteEggCollection = async (date: string) => {
    try {
      await supabase.from('egg_collections').delete().eq('date', date);
    } catch (err) {
      console.error('Failed to delete egg collection:', err);
    }
  };

  const addEggSale = async (sale: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => {
    const saleId = `s-${Date.now()}`;
    const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
    const newSale = {
      id: saleId,
      invoice_id: invoiceNum,
      type: 'Egg',
      date: sale.date,
      customer_name: sale.customerName,
      customer_contact: sale.customerContact,
      quantity: sale.quantity,
      unit_price: sale.unitPrice,
      total_amount: sale.totalAmount,
      details: sale.details
    };
    await supabase.from('sales').insert(newSale);
  };

  const deleteSale = async (saleId: string) => {
    try {
      const sale = sales.find(s => s.id === saleId);
      if (!sale) return;

      const operations: any[] = [supabase.from('sales').delete().eq('id', saleId)];

      if (sale.type === 'Bird' && sale.batchId) {
        const { data: batch } = await supabase
          .from('batches')
          .select('current_quantity')
          .eq('id', sale.batchId)
          .single();

        if (batch) {
          const newQty = batch.current_quantity + sale.quantity;
          operations.push(
            supabase
              .from('batches')
              .update({ current_quantity: newQty, status: 'Active' })
              .eq('id', sale.batchId)
          );
        }
      }

      await Promise.all(operations);
    } catch (err) {
      console.error('Failed to delete sale:', err);
    }
  };

  // 5. Expense Management
  const addExpense = async (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => {
    const newExpense = {
      id: `exp-${Date.now()}`,
      category: expense.category,
      date: expense.date,
      description: expense.description,
      amount: expense.amount,
      is_auto_generated: false
    };
    await supabase.from('expenses').insert(newExpense);
  };

  const deleteExpense = async (id: string) => {
    try {
      const { data: expense } = await supabase
        .from('expenses')
        .select('*')
        .eq('id', id)
        .single();

      if (!expense) return;

      await supabase.from('expenses').delete().eq('id', id);

      if (expense.is_auto_generated && expense.reference_id) {
        if (expense.category === 'Feed') {
          await supabase.from('feed_purchases').delete().eq('id', expense.reference_id);
        } else if (expense.category === 'Medicine') {
          await supabase.from('medical_records').delete().eq('id', expense.reference_id);
        }
      }
    } catch (err) {
      console.error('Failed to delete expense:', err);
    }
  };

  return (
    <FarmContext.Provider
      value={{
        currentUser,
        login,
        logout,
        batches,
        addBatch,
        deleteBatch,
        sellBatch,
        logMortality,
        feedPurchases,
        addFeedPurchase,
        feedConsumption,
        addFeedConsumption,
        vaccines,
        addVaccineSchedule,
        updateVaccineStatus,
        deleteVaccineSchedule,
        medicalRecords,
        addMedicalRecord,
        eggCollections,
        addEggCollection,
        deleteEggCollection,
        sales,
        addEggSale,
        deleteSale,
        expenses,
        addExpense,
        deleteExpense,
        getFeedStock,
        isLoading
      }}
    >
      {children}
    </FarmContext.Provider>
  );
};

export const useFarm = () => {
  const context = useContext(FarmContext);
  if (!context) {
    throw new Error('useFarm must be used within a FarmProvider');
  }
  return context;
};

