import React, { createContext, useContext, useState, useEffect } from 'react';

// ==========================================
// TYPES AND INTERFACES
// ==========================================

export type BirdType = 'Broiler' | 'Layer';
export type BatchStatus = 'Active' | 'Sold';

export interface MortalityLog {
  id: string;
  date: string;
  quantity: number;
  reason: string;
}

export interface BirdBatch {
  id: string;
  type: BirdType;
  arrivalDate: string;
  initialQuantity: number;
  currentQuantity: number;
  purchasePrice: number; // price per bird
  status: BatchStatus;
  mortalityLogs: MortalityLog[];
}

export type FeedType = 'Starter' | 'Grower' | 'Finisher' | 'Layer Mash';

export interface FeedPurchase {
  id: string;
  date: string;
  feedType: FeedType;
  quantityKg: number;
  cost: number;
  vendor: string;
}

export interface FeedConsumption {
  id: string;
  date: string;
  feedType: FeedType;
  batchId: string;
  quantityKg: number;
}

export type VaccineStatus = 'Pending' | 'Completed';

export interface VaccineSchedule {
  id: string;
  vaccineName: string;
  batchId: string;
  scheduledDate: string;
  status: VaccineStatus;
}

export interface MedicalRecord {
  id: string;
  date: string;
  batchId: string;
  disease: string;
  medicine: string;
  dosage: string;
  cost: number;
}

export interface EggCollection {
  date: string;
  collectedQty: number;
  damagedQty: number;
  netQty: number;
}

export type SaleType = 'Bird' | 'Egg';

export interface Sale {
  id: string;
  invoiceId: string;
  type: SaleType;
  date: string;
  customerName: string;
  customerContact: string;
  quantity: number; // number of birds or crates (30 eggs/crate)
  unitPrice: number;
  totalAmount: number;
  batchId?: string; // If bird sale
  details?: string;
}

export type ExpenseCategory = 'Feed' | 'Medicine' | 'Electricity' | 'Labor' | 'Water' | 'Other';

export interface Expense {
  id: string;
  category: ExpenseCategory;
  date: string;
  description: string;
  amount: number;
  isAutoGenerated: boolean;
  referenceId?: string; // ID of feed purchase or medical record
}

export type UserRole = 'Admin' | 'Employee';

export interface User {
  username: string;
  role: UserRole;
}

interface FarmContextType {
  currentUser: User | null;
  login: (username: string, role: UserRole) => boolean;
  logout: () => void;
  batches: BirdBatch[];
  addBatch: (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => void;
  sellBatch: (batchId: string, quantity: number, pricePerBird: number, customerName: string, customerContact: string) => void;
  logMortality: (batchId: string, quantity: number, reason: string, date: string) => void;
  feedPurchases: FeedPurchase[];
  addFeedPurchase: (purchase: Omit<FeedPurchase, 'id'>) => void;
  feedConsumption: FeedConsumption[];
  addFeedConsumption: (consumption: Omit<FeedConsumption, 'id'>) => void;
  vaccines: VaccineSchedule[];
  addVaccineSchedule: (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => void;
  updateVaccineStatus: (id: string, status: VaccineStatus) => void;
  medicalRecords: MedicalRecord[];
  addMedicalRecord: (record: Omit<MedicalRecord, 'id'>) => void;
  eggCollections: EggCollection[];
  addEggCollection: (collection: EggCollection) => void;
  sales: Sale[];
  addEggSale: (sale: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => void;
  expenses: Expense[];
  addExpense: (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => void;
  deleteExpense: (id: string) => void;
  getFeedStock: (type: FeedType) => number;
}

// ==========================================
// INITIAL MOCK DATA
// ==========================================

const INITIAL_BATCHES: BirdBatch[] = [
  {
    id: 'B-101',
    type: 'Layer',
    arrivalDate: '2026-05-15',
    initialQuantity: 1200,
    currentQuantity: 1192,
    purchasePrice: 1.50,
    status: 'Active',
    mortalityLogs: [
      { id: 'm-1', date: '2026-05-20', quantity: 3, reason: 'Stress from transport' },
      { id: 'm-2', date: '2026-05-28', quantity: 5, reason: 'Heat exhaustion' }
    ]
  },
  {
    id: 'B-102',
    type: 'Broiler',
    arrivalDate: '2026-05-28',
    initialQuantity: 1500,
    currentQuantity: 1488,
    purchasePrice: 1.10,
    status: 'Active',
    mortalityLogs: [
      { id: 'm-3', date: '2026-06-02', quantity: 8, reason: 'Coccidiosis outbreak' },
      { id: 'm-4', date: '2026-06-08', quantity: 4, reason: 'Smothering' }
    ]
  },
  {
    id: 'B-99',
    type: 'Broiler',
    arrivalDate: '2026-04-10',
    initialQuantity: 1000,
    currentQuantity: 0,
    purchasePrice: 1.05,
    status: 'Sold',
    mortalityLogs: [
      { id: 'm-5', date: '2026-04-15', quantity: 10, reason: 'Temperature fluctuation' }
    ]
  }
];

const INITIAL_FEED_PURCHASES: FeedPurchase[] = [
  { id: 'fp-1', date: '2026-05-10', feedType: 'Layer Mash', quantityKg: 1500, cost: 675, vendor: 'AgriFeed Co.' },
  { id: 'fp-2', date: '2026-05-25', feedType: 'Starter', quantityKg: 800, cost: 420, vendor: 'Poultry Nutrition Ltd' },
  { id: 'fp-3', date: '2026-06-01', feedType: 'Grower', quantityKg: 1000, cost: 480, vendor: 'Poultry Nutrition Ltd' }
];

const INITIAL_FEED_CONSUMPTION: FeedConsumption[] = [
  // Layer mash consumption (B-101)
  { id: 'fc-1', date: '2026-06-05', feedType: 'Layer Mash', batchId: 'B-101', quantityKg: 60 },
  { id: 'fc-2', date: '2026-06-06', feedType: 'Layer Mash', batchId: 'B-101', quantityKg: 62 },
  { id: 'fc-3', date: '2026-06-07', feedType: 'Layer Mash', batchId: 'B-101', quantityKg: 59 },
  { id: 'fc-4', date: '2026-06-08', feedType: 'Layer Mash', batchId: 'B-101', quantityKg: 61 },
  { id: 'fc-5', date: '2026-06-09', feedType: 'Layer Mash', batchId: 'B-101', quantityKg: 65 },
  { id: 'fc-6', date: '2026-06-10', feedType: 'Layer Mash', batchId: 'B-101', quantityKg: 63 },
  { id: 'fc-7', date: '2026-06-11', feedType: 'Layer Mash', batchId: 'B-101', quantityKg: 64 },

  // Starter/Grower consumption (B-102)
  { id: 'fc-8', date: '2026-06-08', feedType: 'Starter', batchId: 'B-102', quantityKg: 75 },
  { id: 'fc-9', date: '2026-06-09', feedType: 'Starter', batchId: 'B-102', quantityKg: 78 },
  { id: 'fc-10', date: '2026-06-10', feedType: 'Grower', batchId: 'B-102', quantityKg: 82 },
  { id: 'fc-11', date: '2026-06-11', feedType: 'Grower', batchId: 'B-102', quantityKg: 85 }
];

const INITIAL_VACCINES: VaccineSchedule[] = [
  { id: 'v-1', vaccineName: 'Newcastle Disease', batchId: 'B-101', scheduledDate: '2026-05-22', status: 'Completed' },
  { id: 'v-2', vaccineName: 'Gumboro Disease', batchId: 'B-101', scheduledDate: '2026-06-05', status: 'Completed' },
  { id: 'v-3', vaccineName: 'Fowl Pox', batchId: 'B-101', scheduledDate: '2026-06-25', status: 'Pending' },
  { id: 'v-4', vaccineName: 'Newcastle Disease', batchId: 'B-102', scheduledDate: '2026-06-04', status: 'Completed' },
  { id: 'v-5', vaccineName: 'Infectious Bronchitis', batchId: 'B-102', scheduledDate: '2026-06-18', status: 'Pending' }
];

const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  { id: 'mr-1', date: '2026-06-02', batchId: 'B-102', disease: 'Coccidiosis', medicine: 'Amprolium', dosage: '9.6% solution in water for 5 days', cost: 120 }
];

const INITIAL_EGGS: EggCollection[] = [
  { date: '2026-06-02', collectedQty: 820, damagedQty: 12, netQty: 808 },
  { date: '2026-06-03', collectedQty: 840, damagedQty: 10, netQty: 830 },
  { date: '2026-06-04', collectedQty: 850, damagedQty: 15, netQty: 835 },
  { date: '2026-06-05', collectedQty: 810, damagedQty: 8, netQty: 802 },
  { date: '2026-06-06', collectedQty: 830, damagedQty: 14, netQty: 816 },
  { date: '2026-06-07', collectedQty: 860, damagedQty: 9, netQty: 851 },
  { date: '2026-06-08', collectedQty: 875, damagedQty: 11, netQty: 864 },
  { date: '2026-06-09', collectedQty: 890, damagedQty: 7, netQty: 883 },
  { date: '2026-06-10', collectedQty: 910, damagedQty: 10, netQty: 900 },
  { date: '2026-06-11', collectedQty: 925, damagedQty: 8, netQty: 917 }
];

const INITIAL_SALES: Sale[] = [
  {
    id: 's-1',
    invoiceId: 'INV-2026-0001',
    type: 'Bird',
    date: '2026-05-24',
    customerName: 'Premium Meat Market',
    customerContact: '+1 (555) 019-2834',
    quantity: 990, // B-99 batch (1000 - 10 mortality)
    unitPrice: 4.50, // Per bird
    totalAmount: 4455,
    batchId: 'B-99',
    details: 'Full batch B-99 Broilers sold. Avg weight ~2.1kg.'
  },
  {
    id: 's-2',
    invoiceId: 'INV-2026-0002',
    type: 'Egg',
    date: '2026-06-06',
    customerName: 'Daily Delights Bakery',
    customerContact: '+1 (555) 014-9988',
    quantity: 50, // Crates
    unitPrice: 5.50, // Per crate
    totalAmount: 275,
    details: '1500 clean layer eggs (50 crates of 30).'
  },
  {
    id: 's-3',
    invoiceId: 'INV-2026-0003',
    type: 'Egg',
    date: '2026-06-10',
    customerName: 'Supermart Distributors',
    customerContact: '+1 (555) 012-4411',
    quantity: 120, // Crates
    unitPrice: 5.30,
    totalAmount: 636,
    details: '3600 fresh eggs (120 crates of 30).'
  }
];

const INITIAL_EXPENSES: Expense[] = [
  // Auto-generated from feed purchases
  { id: 'exp-1', category: 'Feed', date: '2026-05-10', description: 'Feed Purchase: Layer Mash (1500 kg) from AgriFeed Co.', amount: 675, isAutoGenerated: true, referenceId: 'fp-1' },
  { id: 'exp-2', category: 'Feed', date: '2026-05-25', description: 'Feed Purchase: Starter (800 kg) from Poultry Nutrition Ltd', amount: 420, isAutoGenerated: true, referenceId: 'fp-2' },
  { id: 'exp-3', category: 'Feed', date: '2026-06-01', description: 'Feed Purchase: Grower (1000 kg) from Poultry Nutrition Ltd', amount: 480, isAutoGenerated: true, referenceId: 'fp-3' },
  
  // Auto-generated from health purchases
  { id: 'exp-4', category: 'Medicine', date: '2026-06-02', description: 'Medical Record Treatment: Coccidiosis in B-102 (Amprolium)', amount: 120, isAutoGenerated: true, referenceId: 'mr-1' },
  
  // Manual expenses
  { id: 'exp-5', category: 'Electricity', date: '2026-05-30', description: 'Farm shed ventilation and lighting electricity bill - May', amount: 245, isAutoGenerated: false },
  { id: 'exp-6', category: 'Labor', date: '2026-05-31', description: 'Part-time farm hands wage payout', amount: 900, isAutoGenerated: false },
  { id: 'exp-7', category: 'Water', date: '2026-05-31', description: 'Water supply utility charges - May', amount: 95, isAutoGenerated: false },
  { id: 'exp-8', category: 'Other', date: '2026-06-05', description: 'Repairs for automated drinker lines in Shed 2', amount: 130, isAutoGenerated: false }
];

// ==========================================
// CONTEXT CREATION & PROVIDER
// ==========================================

const FarmContext = createContext<FarmContextType | undefined>(undefined);

export const FarmProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Session User
  const [currentUser, setCurrentUser] = useState<User | null>(() => {
    const saved = localStorage.getItem('poultry_user');
    return saved ? JSON.parse(saved) : null;
  });

  // Core Farm States
  const [batches, setBatches] = useState<BirdBatch[]>(() => {
    const saved = localStorage.getItem('poultry_batches');
    return saved ? JSON.parse(saved) : INITIAL_BATCHES;
  });

  const [feedPurchases, setFeedPurchases] = useState<FeedPurchase[]>(() => {
    const saved = localStorage.getItem('poultry_feed_purchases');
    return saved ? JSON.parse(saved) : INITIAL_FEED_PURCHASES;
  });

  const [feedConsumption, setFeedConsumption] = useState<FeedConsumption[]>(() => {
    const saved = localStorage.getItem('poultry_feed_consumption');
    return saved ? JSON.parse(saved) : INITIAL_FEED_CONSUMPTION;
  });

  const [vaccines, setVaccines] = useState<VaccineSchedule[]>(() => {
    const saved = localStorage.getItem('poultry_vaccines');
    return saved ? JSON.parse(saved) : INITIAL_VACCINES;
  });

  const [medicalRecords, setMedicalRecords] = useState<MedicalRecord[]>(() => {
    const saved = localStorage.getItem('poultry_medical_records');
    return saved ? JSON.parse(saved) : INITIAL_MEDICAL_RECORDS;
  });

  const [eggCollections, setEggCollections] = useState<EggCollection[]>(() => {
    const saved = localStorage.getItem('poultry_egg_collections');
    return saved ? JSON.parse(saved) : INITIAL_EGGS;
  });

  const [sales, setSales] = useState<Sale[]>(() => {
    const saved = localStorage.getItem('poultry_sales');
    return saved ? JSON.parse(saved) : INITIAL_SALES;
  });

  const [expenses, setExpenses] = useState<Expense[]>(() => {
    const saved = localStorage.getItem('poultry_expenses');
    return saved ? JSON.parse(saved) : INITIAL_EXPENSES;
  });

  // Save changes to LocalStorage
  useEffect(() => {
    localStorage.setItem('poultry_user', currentUser ? JSON.stringify(currentUser) : '');
  }, [currentUser]);

  useEffect(() => {
    localStorage.setItem('poultry_batches', JSON.stringify(batches));
  }, [batches]);

  useEffect(() => {
    localStorage.setItem('poultry_feed_purchases', JSON.stringify(feedPurchases));
  }, [feedPurchases]);

  useEffect(() => {
    localStorage.setItem('poultry_feed_consumption', JSON.stringify(feedConsumption));
  }, [feedConsumption]);

  useEffect(() => {
    localStorage.setItem('poultry_vaccines', JSON.stringify(vaccines));
  }, [vaccines]);

  useEffect(() => {
    localStorage.setItem('poultry_medical_records', JSON.stringify(medicalRecords));
  }, [medicalRecords]);

  useEffect(() => {
    localStorage.setItem('poultry_egg_collections', JSON.stringify(eggCollections));
  }, [eggCollections]);

  useEffect(() => {
    localStorage.setItem('poultry_sales', JSON.stringify(sales));
  }, [sales]);

  useEffect(() => {
    localStorage.setItem('poultry_expenses', JSON.stringify(expenses));
  }, [expenses]);

  // ==========================================
  // UTILITIES & STATE MUTATORS
  // ==========================================

  // Authentication
  const login = (username: string, role: UserRole): boolean => {
    // Basic password checking - accepts 'admin' / 'employee' for simplicity
    if (
      (role === 'Admin' && username.toLowerCase() === 'admin') ||
      (role === 'Employee' && username.toLowerCase() === 'employee')
    ) {
      setCurrentUser({ username, role });
      return true;
    }
    return false;
  };

  const logout = () => {
    setCurrentUser(null);
  };

  // 1. Bird Management
  const addBatch = (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => {
    const newBatch: BirdBatch = {
      ...batch,
      currentQuantity: batch.initialQuantity,
      status: 'Active',
      mortalityLogs: []
    };
    setBatches(prev => [newBatch, ...prev]);

    // Track original bird cost as immediate expense
    const cost = batch.initialQuantity * batch.purchasePrice;
    const newExpense: Expense = {
      id: `exp-${Date.now()}`,
      category: 'Other',
      date: batch.arrivalDate,
      description: `Bird Batch Purchase: ${batch.type} - ${batch.initialQuantity} birds (ID: ${batch.id})`,
      amount: cost,
      isAutoGenerated: true,
      referenceId: batch.id
    };
    setExpenses(prev => [newExpense, ...prev]);
  };

  const sellBatch = (
    batchId: string,
    quantity: number,
    pricePerBird: number,
    customerName: string,
    customerContact: string
  ) => {
    setBatches(prev =>
      prev.map(b => {
        if (b.id === batchId) {
          const newCurrentQty = Math.max(0, b.currentQuantity - quantity);
          return {
            ...b,
            currentQuantity: newCurrentQty,
            status: newCurrentQty === 0 ? 'Sold' : 'Active'
          };
        }
        return b;
      })
    );

    // Record sale
    const saleId = `s-${Date.now()}`;
    const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
    const newSale: Sale = {
      id: saleId,
      invoiceId: invoiceNum,
      type: 'Bird',
      date: new Date().toISOString().split('T')[0],
      customerName,
      customerContact,
      quantity,
      unitPrice: pricePerBird,
      totalAmount: quantity * pricePerBird,
      batchId,
      details: `Sold ${quantity} birds from Batch ${batchId}`
    };
    setSales(prev => [newSale, ...prev]);
  };

  const logMortality = (batchId: string, quantity: number, reason: string, date: string) => {
    setBatches(prev =>
      prev.map(b => {
        if (b.id === batchId) {
          const actualQty = Math.min(b.currentQuantity, quantity);
          const newLogs = [
            ...b.mortalityLogs,
            { id: `m-${Date.now()}`, date, quantity: actualQty, reason }
          ];
          return {
            ...b,
            currentQuantity: b.currentQuantity - actualQty,
            mortalityLogs: newLogs
          };
        }
        return b;
      })
    );
  };

  // 2. Feed Management
  const addFeedPurchase = (purchase: Omit<FeedPurchase, 'id'>) => {
    const id = `fp-${Date.now()}`;
    const newPurchase: FeedPurchase = { id, ...purchase };
    setFeedPurchases(prev => [newPurchase, ...prev]);

    // Auto add to expenses
    const newExpense: Expense = {
      id: `exp-${Date.now()}`,
      category: 'Feed',
      date: purchase.date,
      description: `Feed Purchase: ${purchase.feedType} (${purchase.quantityKg} kg) from ${purchase.vendor}`,
      amount: purchase.cost,
      isAutoGenerated: true,
      referenceId: id
    };
    setExpenses(prev => [newExpense, ...prev]);
  };

  const addFeedConsumption = (consumption: Omit<FeedConsumption, 'id'>) => {
    const id = `fc-${Date.now()}`;
    const newConsumption: FeedConsumption = { id, ...consumption };
    setFeedConsumption(prev => [newConsumption, ...prev]);
  };

  const getFeedStock = (type: FeedType): number => {
    const totalPurchased = feedPurchases
      .filter(p => p.feedType === type)
      .reduce((sum, p) => sum + p.quantityKg, 0);

    const totalConsumed = feedConsumption
      .filter(c => c.feedType === type)
      .reduce((sum, c) => sum + c.quantityKg, 0);

    return Math.max(0, totalPurchased - totalConsumed);
  };

  // 3. Health & Vaccination
  const addVaccineSchedule = (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => {
    const newSchedule: VaccineSchedule = {
      id: `v-${Date.now()}`,
      ...schedule,
      status: 'Pending'
    };
    setVaccines(prev => [newSchedule, ...prev]);
  };

  const updateVaccineStatus = (id: string, status: VaccineStatus) => {
    setVaccines(prev =>
      prev.map(v => (v.id === id ? { ...v, status } : v))
    );
  };

  const addMedicalRecord = (record: Omit<MedicalRecord, 'id'>) => {
    const id = `mr-${Date.now()}`;
    const newRecord: MedicalRecord = { id, ...record };
    setMedicalRecords(prev => [newRecord, ...prev]);

    // Auto-generate medical expense
    if (record.cost > 0) {
      const newExpense: Expense = {
        id: `exp-${Date.now()}`,
        category: 'Medicine',
        date: record.date,
        description: `Medical Treatment: Batch ${record.batchId} treated for ${record.disease} (${record.medicine})`,
        amount: record.cost,
        isAutoGenerated: true,
        referenceId: id
      };
      setExpenses(prev => [newExpense, ...prev]);
    }
  };

  // 4. Egg Production
  const addEggCollection = (collection: EggCollection) => {
    // Check if entry for date already exists, if so overwrite, else prepend
    setEggCollections(prev => {
      const filtered = prev.filter(c => c.date !== collection.date);
      return [collection, ...filtered].sort((a, b) => b.date.localeCompare(a.date));
    });
  };

  const addEggSale = (sale: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => {
    const saleId = `s-${Date.now()}`;
    const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
    const newSale: Sale = {
      id: saleId,
      invoiceId: invoiceNum,
      type: 'Egg',
      date: sale.date,
      customerName: sale.customerName,
      customerContact: sale.customerContact,
      quantity: sale.quantity,
      unitPrice: sale.unitPrice,
      totalAmount: sale.totalAmount,
      details: sale.details
    };
    setSales(prev => [newSale, ...prev]);
  };

  // 5. Expense Management
  const addExpense = (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => {
    const newExpense: Expense = {
      id: `exp-${Date.now()}`,
      ...expense,
      isAutoGenerated: false
    };
    setExpenses(prev => [newExpense, ...prev]);
  };

  const deleteExpense = (id: string) => {
    // Warning: Normally auto-generated expenses should be kept or deleted along with references,
    // but we allow deletion or standard control from context.
    const expense = expenses.find(e => e.id === id);
    if (!expense) return;

    setExpenses(prev => prev.filter(e => e.id !== id));

    // If it's a feed purchase reference, clean it up from purchases as well
    if (expense.isAutoGenerated && expense.referenceId) {
      if (expense.category === 'Feed') {
        setFeedPurchases(prev => prev.filter(p => p.id !== expense.referenceId));
      } else if (expense.category === 'Medicine') {
        setMedicalRecords(prev => prev.filter(m => m.id !== expense.referenceId));
      }
    }
  };

  return (
    <FarmContext.Provider
      value={{
        currentUser,
        login,
        logout,
        batches,
        addBatch,
        sellBatch,
        logMortality,
        feedPurchases,
        addFeedPurchase,
        feedConsumption,
        addFeedConsumption,
        vaccines,
        addVaccineSchedule,
        updateVaccineStatus,
        medicalRecords,
        addMedicalRecord,
        eggCollections,
        addEggCollection,
        sales,
        addEggSale,
        expenses,
        addExpense,
        deleteExpense,
        getFeedStock
      }}
    >
      {children}
    </FarmContext.Provider>
  );
};

export const useFarm = () => {
  const context = useContext(FarmContext);
  if (!context) {
    throw new Error('useFarm must be used within a FarmProvider');
  }
  return context;
};
