import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../lib/supabaseClient';

// ==========================================
// TYPES AND INTERFACES
// ==========================================

export type BirdType = 'Broiler' | 'Layer';
export type BatchStatus = 'Active' | 'Sold';

export interface MortalityLog {
  id: string;
  date: string;
  quantity: number;
  reason: string;
}

export interface BirdBatch {
  id: string;
  type: BirdType;
  arrivalDate: string;
  initialQuantity: number;
  currentQuantity: number;
  purchasePrice: number; // price per bird
  status: BatchStatus;
  mortalityLogs: MortalityLog[];
  initialQuantityKg?: number;
  purchasePricePerKg?: number;
}

export type FeedType = 'Starter' | 'Grower' | 'Finisher' | 'Layer Mash';

export interface FeedPurchase {
  id: string;
  date: string;
  feedType: FeedType;
  quantityKg: number;
  cost: number;
  vendor: string;
}

export interface FeedConsumption {
  id: string;
  date: string;
  feedType: FeedType;
  batchId: string;
  quantityKg: number;
}

export type VaccineStatus = 'Pending' | 'Completed';

export interface VaccineSchedule {
  id: string;
  vaccineName: string;
  batchId: string;
  scheduledDate: string;
  status: VaccineStatus;
}

export interface MedicalRecord {
  id: string;
  date: string;
  batchId: string;
  disease: string;
  medicine: string;
  dosage: string;
  cost: number;
}

export interface EggCollection {
  date: string;
  collectedQty: number;
  damagedQty: number;
  netQty: number;
}

export type SaleType = 'Bird' | 'Egg';

export interface Sale {
  id: string;
  invoiceId: string;
  type: SaleType;
  date: string;
  customerName: string;
  customerContact: string;
  quantity: number; // number of birds or crates (30 eggs/crate)
  unitPrice: number;
  totalAmount: number;
  batchId?: string; // If bird sale
  details?: string;
}

export type ExpenseCategory = 'Feed' | 'Medicine' | 'Electricity' | 'Labor' | 'Water' | 'Other';

export interface Expense {
  id: string;
  category: ExpenseCategory;
  date: string;
  description: string;
  amount: number;
  isAutoGenerated: boolean;
  referenceId?: string; // ID of feed purchase or medical record
}

export type UserRole = 'Admin' | 'Employee';

export interface User {
  username: string;
  role: UserRole;
}

interface FarmContextType {
  currentUser: User | null;
  login: (username: string, role: UserRole) => boolean;
  logout: () => void;
  batches: BirdBatch[];
  addBatch: (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => void;
  deleteBatch: (batchId: string) => void;
  sellBatch: (batchId: string, quantity: number, pricePerBird: number, customerName: string, customerContact: string) => void;
  logMortality: (batchId: string, quantity: number, reason: string, date: string) => void;
  feedPurchases: FeedPurchase[];
  addFeedPurchase: (purchase: Omit<FeedPurchase, 'id'>) => void;
  feedConsumption: FeedConsumption[];
  addFeedConsumption: (consumption: Omit<FeedConsumption, 'id'>) => void;
  vaccines: VaccineSchedule[];
  addVaccineSchedule: (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => void;
  updateVaccineStatus: (id: string, status: VaccineStatus) => void;
  deleteVaccineSchedule: (id: string) => void;
  medicalRecords: MedicalRecord[];
  addMedicalRecord: (record: Omit<MedicalRecord, 'id'>) => void;
  eggCollections: EggCollection[];
  addEggCollection: (collection: EggCollection) => void;
  deleteEggCollection: (date: string) => void;
  sales: Sale[];
  addEggSale: (sale: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => void;
  deleteSale: (saleId: string) => Promise<void>;
  expenses: Expense[];
  addExpense: (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => void;
  deleteExpense: (id: string) => void;
  getFeedStock: (type: FeedType) => number;
  updateBatch: (batchId: string, updated: Omit<BirdBatch, 'id' | 'mortalityLogs'>) => Promise<void>;
  updateFeedPurchase: (purchaseId: string, updated: Omit<FeedPurchase, 'id'>) => Promise<void>;
  updateFeedConsumption: (consumptionId: string, updated: Omit<FeedConsumption, 'id'>) => Promise<void>;
  updateVaccineSchedule: (id: string, updated: Omit<VaccineSchedule, 'id'>) => Promise<void>;
  updateMedicalRecord: (recordId: string, updated: Omit<MedicalRecord, 'id'>) => Promise<void>;
  updateEggCollection: (originalDate: string, updated: EggCollection) => Promise<void>;
  updateSale: (saleId: string, updated: Omit<Sale, 'id' | 'invoiceId'>) => Promise<void>;
  updateExpense: (id: string, updated: Omit<Expense, 'id' | 'isAutoGenerated'>) => Promise<void>;
  isLoading: boolean;
}

// ==========================================
// CONTEXT CREATION & PROVIDER
// ==========================================

const FarmContext = createContext<FarmContextType | undefined>(undefined);

export const FarmProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Session User (Kept in LocalStorage for dev auth simplicity)
  const [currentUser, setCurrentUser] = useState<User | null>(() => {
    try {
      const saved = localStorage.getItem('poultry_user');
      if (!saved) return null;
      const parsed = JSON.parse(saved);
      // Validate shape to guard against tampered storage
      if (
        parsed &&
        typeof parsed.username === 'string' &&
        (parsed.role === 'Admin' || parsed.role === 'Employee')
      ) {
        return parsed as User;
      }
      return null;
    } catch {
      localStorage.removeItem('poultry_user');
      return null;
    }
  });

  // Core Farm States
  const [batches, setBatches] = useState<BirdBatch[]>([]);
  const [feedPurchases, setFeedPurchases] = useState<FeedPurchase[]>([]);
  const [feedConsumption, setFeedConsumption] = useState<FeedConsumption[]>([]);
  const [vaccines, setVaccines] = useState<VaccineSchedule[]>([]);
  const [medicalRecords, setMedicalRecords] = useState<MedicalRecord[]>([]);
  const [eggCollections, setEggCollections] = useState<EggCollection[]>([]);
  const [sales, setSales] = useState<Sale[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // ----------------------------------------------------
  // FETCH ALL DATA FROM SUPABASE
  // ----------------------------------------------------
  const fetchAllData = async () => {
    try {
      const [
        { data: batchesData, error: batchesErr },
        { data: mortalityData, error: mortalityErr },
        { data: feedPurchasesData, error: fpErr },
        { data: feedConsumptionData, error: fcErr },
        { data: vaccinesData, error: vErr },
        { data: medicalRecordsData, error: mrErr },
        { data: eggCollectionsData, error: ecErr },
        { data: salesData, error: sErr },
        { data: expensesData, error: expErr }
      ] = await Promise.all([
        supabase.from('batches').select('*'),
        supabase.from('mortality_logs').select('*'),
        supabase.from('feed_purchases').select('*'),
        supabase.from('feed_consumptions').select('*'),
        supabase.from('vaccine_schedules').select('*'),
        supabase.from('medical_records').select('*'),
        supabase.from('egg_collections').select('*'),
        supabase.from('sales').select('*'),
        supabase.from('expenses').select('*')
      ]);

      if (batchesErr || mortalityErr || fpErr || fcErr || vErr || mrErr || ecErr || sErr || expErr) {
        console.error('Error fetching data from Supabase:', {
          batchesErr, mortalityErr, fpErr, fcErr, vErr, mrErr, ecErr, sErr, expErr
        });
        return;
      }

      // Map Batches and their Mortality Logs
      const formattedBatches = (batchesData || []).map((b: any) => ({
        id: b.id,
        type: b.type as BirdType,
        arrivalDate: b.arrival_date,
        initialQuantity: b.initial_quantity,
        currentQuantity: b.current_quantity,
        purchasePrice: Number(b.purchase_price),
        status: b.status as BatchStatus,
        initialQuantityKg: b.initial_quantity_kg ? Number(b.initial_quantity_kg) : undefined,
        purchasePricePerKg: b.purchase_price_per_kg ? Number(b.purchase_price_per_kg) : undefined,
        mortalityLogs: (mortalityData || [])
          .filter((m: any) => m.batch_id === b.id)
          .map((m: any) => ({
            id: m.id,
            date: m.date,
            quantity: m.quantity,
            reason: m.reason
          }))
      }));
      setBatches(formattedBatches);

      // Map Feed Purchases
      setFeedPurchases((feedPurchasesData || []).map((p: any) => ({
        id: p.id,
        date: p.date,
        feedType: p.feed_type as FeedType,
        quantityKg: Number(p.quantity_kg),
        cost: Number(p.cost),
        vendor: p.vendor
      })));

      // Map Feed Consumptions
      setFeedConsumption((feedConsumptionData || []).map((c: any) => ({
        id: c.id,
        date: c.date,
        feedType: c.feed_type as FeedType,
        batchId: c.batch_id,
        quantityKg: Number(c.quantity_kg)
      })));

      // Map Vaccine Schedules
      setVaccines((vaccinesData || []).map((v: any) => ({
        id: v.id,
        vaccineName: v.vaccine_name,
        batchId: v.batch_id,
        scheduledDate: v.scheduled_date,
        status: v.status as VaccineStatus
      })));

      // Map Medical Records
      setMedicalRecords((medicalRecordsData || []).map((m: any) => ({
        id: m.id,
        date: m.date,
        batchId: m.batch_id,
        disease: m.disease,
        medicine: m.medicine,
        dosage: m.dosage,
        cost: Number(m.cost)
      })));

      // Map Egg Collections
      setEggCollections((eggCollectionsData || []).map((e: any) => ({
        date: e.date,
        collectedQty: e.collected_qty,
        damagedQty: e.damaged_qty,
        netQty: e.net_qty
      })));

      // Map Sales
      setSales((salesData || []).map((s: any) => ({
        id: s.id,
        invoiceId: s.invoice_id,
        type: s.type as SaleType,
        date: s.date,
        customerName: s.customer_name,
        customerContact: s.customer_contact,
        quantity: Number(s.quantity),
        unitPrice: Number(s.unit_price),
        totalAmount: Number(s.total_amount),
        batchId: s.batch_id || undefined,
        details: s.details || undefined
      })));

      // Map Expenses
      setExpenses((expensesData || []).map((ex: any) => ({
        id: ex.id,
        category: ex.category as ExpenseCategory,
        date: ex.date,
        description: ex.description,
        amount: Number(ex.amount),
        isAutoGenerated: ex.is_auto_generated,
        referenceId: ex.reference_id || undefined
      })));

    } catch (err) {
      console.error('Unexpected error loading farm data:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Sync session user
  useEffect(() => {
    if (currentUser) {
      localStorage.setItem('poultry_user', JSON.stringify(currentUser));
    } else {
      localStorage.removeItem('poultry_user');
    }
  }, [currentUser]);

  // Load initial data and subscribe to realtime updates
  useEffect(() => {
    fetchAllData();

    // Subscribe to schema changes across all public tables
    const channel = supabase
      .channel('realtime-farm-updates')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public' },
        () => {
          // Trigger a clean refetch when any database write occurs
          fetchAllData();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  // ==========================================
  // UTILITIES & STATE MUTATORS
  // ==========================================

  // Authentication (Local Session storage)
  const login = (username: string, role: UserRole): boolean => {
    // Validate that the username is a non-empty string and role is an allowed value
    const trimmed = username.trim();
    if (!trimmed || trimmed.length > 64) return false;
    if (role !== 'Admin' && role !== 'Employee') return false;

    if (
      (role === 'Admin' && trimmed.toLowerCase() === 'admin') ||
      (role === 'Employee' && trimmed.toLowerCase() === 'employee')
    ) {
      setCurrentUser({ username: trimmed, role });
      return true;
    }
    return false;
  };

  const logout = () => {
    setCurrentUser(null);
  };

  // 1. Bird Management
  const addBatch = async (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => {
    const newBatch: any = {
      id: batch.id,
      type: batch.type,
      arrival_date: batch.arrivalDate,
      initial_quantity: batch.initialQuantity,
      current_quantity: batch.initialQuantity,
      purchase_price: batch.purchasePrice,
      status: 'Active',
      initial_quantity_kg: batch.type === 'Broiler' ? batch.initialQuantityKg : null,
      purchase_price_per_kg: batch.type === 'Broiler' ? batch.purchasePricePerKg : null
    };

    const cost = batch.type === 'Broiler' && batch.initialQuantityKg && batch.purchasePricePerKg
      ? batch.initialQuantityKg * batch.purchasePricePerKg
      : batch.initialQuantity * batch.purchasePrice;

    const newExpense = {
      id: `exp-${Date.now()}`,
      category: 'Other',
      date: batch.arrivalDate,
      description: `Bird Batch Purchase: ${batch.type} - ${batch.initialQuantity} birds (ID: ${batch.id})`,
      amount: cost,
      is_auto_generated: true,
      reference_id: batch.id
    };

    try {
      const { error: batchErr } = await supabase.from('batches').insert(newBatch);
      if (batchErr) {
        if (batchErr.code === 'PGRST204' || batchErr.message?.includes('initial_quantity_kg') || batchErr.message?.includes('schema cache')) {
          console.warn("Supabase schema cache missing initial_quantity_kg columns. Retrying without these columns.");
          alert("Notice: Broiler weight-based columns (initial_quantity_kg, purchase_price_per_kg) do not exist in your Supabase database. The batch will be saved as a standard bird batch. To enable full weight tracking, please run the SQL migration at the bottom of your schema.sql file in the Supabase SQL Editor.");
          
          delete newBatch.initial_quantity_kg;
          delete newBatch.purchase_price_per_kg;
          
          const { error: retryErr } = await supabase.from('batches').insert(newBatch);
          if (retryErr) throw retryErr;
        } else {
          throw batchErr;
        }
      }

      const { error: expErr } = await supabase.from('expenses').insert(newExpense);
      if (expErr) throw expErr;

      fetchAllData();
    } catch (err: any) {
      console.error('Failed to add batch:', err);
      alert(`Error adding batch: ${err.message || err}`);
    }
  };

  const sellBatch = async (
    batchId: string,
    quantity: number,
    pricePerBird: number,
    customerName: string,
    customerContact: string
  ) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (!batch) return;

      const newCurrentQty = Math.max(0, batch.current_quantity - quantity);
      const newStatus = newCurrentQty === 0 ? 'Sold' : 'Active';

      const saleId = `s-${Date.now()}`;
      const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
      const newSale = {
        id: saleId,
        invoice_id: invoiceNum,
        type: 'Bird',
        date: new Date().toISOString().split('T')[0],
        customer_name: customerName,
        customer_contact: customerContact,
        quantity,
        unit_price: pricePerBird,
        total_amount: quantity * pricePerBird,
        batch_id: batchId,
        details: `Sold ${quantity} birds from Batch ${batchId}`
      };

      await Promise.all([
        supabase
          .from('batches')
          .update({ current_quantity: newCurrentQty, status: newStatus })
          .eq('id', batchId),
        supabase.from('sales').insert(newSale)
      ]);
    } catch (err) {
      console.error('Failed to sell batch:', err);
    }
  };

  const logMortality = async (batchId: string, quantity: number, reason: string, date: string) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (!batch) return;

      const actualQty = Math.min(batch.current_quantity, quantity);
      const newCurrentQty = batch.current_quantity - actualQty;

      const newLog = {
        id: `m-${Date.now()}`,
        batch_id: batchId,
        date,
        quantity: actualQty,
        reason
      };

      await Promise.all([
        supabase
          .from('batches')
          .update({ current_quantity: newCurrentQty })
          .eq('id', batchId),
        supabase.from('mortality_logs').insert(newLog)
      ]);
    } catch (err) {
      console.error('Failed to log mortality:', err);
    }
  };

  const deleteBatch = async (batchId: string) => {
    try {
      // Step 1: Get medical record IDs for this batch so we can delete their linked expenses
      const { data: medRecords } = await supabase
        .from('medical_records')
        .select('id')
        .eq('batch_id', batchId);

      // Step 2: Delete expenses auto-linked to medical records
      if (medRecords && medRecords.length > 0) {
        const medIds = medRecords.map((m: any) => m.id);
        await supabase
          .from('expenses')
          .delete()
          .in('reference_id', medIds)
          .eq('is_auto_generated', true);
      }

      // Step 3: Delete medical records for this batch
      await supabase.from('medical_records').delete().eq('batch_id', batchId);

      // Step 4: Delete vaccine schedules for this batch
      await supabase.from('vaccine_schedules').delete().eq('batch_id', batchId);

      // Step 5: Delete feed consumptions for this batch
      await supabase.from('feed_consumptions').delete().eq('batch_id', batchId);

      // Step 6: Delete mortality logs for this batch
      await supabase.from('mortality_logs').delete().eq('batch_id', batchId);

      // Step 7: Delete the auto-generated batch purchase expense
      await supabase
        .from('expenses')
        .delete()
        .eq('reference_id', batchId)
        .eq('is_auto_generated', true);

      // Step 8: Null out batch_id on any sales (preserve financial history)
      await supabase
        .from('sales')
        .update({ batch_id: null })
        .eq('batch_id', batchId);

      // Step 9: Finally delete the batch itself
      const { error } = await supabase.from('batches').delete().eq('id', batchId);
      if (error) throw error;

    } catch (err: any) {
      console.error('Failed to delete batch:', err);
      alert(`Delete failed: ${err?.message ?? 'Unknown error. Check console for details.'}`);
    }
  };


  const addFeedPurchase = async (purchase: Omit<FeedPurchase, 'id'>) => {
    const id = `fp-${Date.now()}`;
    const newPurchase = {
      id,
      date: purchase.date,
      feed_type: purchase.feedType,
      quantity_kg: purchase.quantityKg,
      cost: purchase.cost,
      vendor: purchase.vendor
    };

    const newExpense = {
      id: `exp-${Date.now()}`,
      category: 'Feed',
      date: purchase.date,
      description: `Feed Purchase: ${purchase.feedType} (${purchase.quantityKg} kg) from ${purchase.vendor}`,
      amount: purchase.cost,
      is_auto_generated: true,
      reference_id: id
    };

    await Promise.all([
      supabase.from('feed_purchases').insert(newPurchase),
      supabase.from('expenses').insert(newExpense)
    ]);
  };

  const addFeedConsumption = async (consumption: Omit<FeedConsumption, 'id'>) => {
    const id = `fc-${Date.now()}`;
    const newConsumption = {
      id,
      date: consumption.date,
      feed_type: consumption.feedType,
      batch_id: consumption.batchId,
      quantity_kg: consumption.quantityKg
    };
    await supabase.from('feed_consumptions').insert(newConsumption);
  };

  const getFeedStock = (type: FeedType): number => {
    const totalPurchased = feedPurchases
      .filter(p => p.feedType === type)
      .reduce((sum, p) => sum + p.quantityKg, 0);

    const totalConsumed = feedConsumption
      .filter(c => c.feedType === type)
      .reduce((sum, c) => sum + c.quantityKg, 0);

    return Math.max(0, totalPurchased - totalConsumed);
  };

  // 3. Health & Vaccination
  const addVaccineSchedule = async (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => {
    const newSchedule = {
      id: `v-${Date.now()}`,
      vaccine_name: schedule.vaccineName,
      batch_id: schedule.batchId,
      scheduled_date: schedule.scheduledDate,
      status: 'Pending'
    };
    await supabase.from('vaccine_schedules').insert(newSchedule);
  };

  const updateVaccineStatus = async (id: string, status: VaccineStatus) => {
    await supabase
      .from('vaccine_schedules')
      .update({ status })
      .eq('id', id);
  };

  const deleteVaccineSchedule = async (id: string) => {
    try {
      await supabase.from('vaccine_schedules').delete().eq('id', id);
    } catch (err) {
      console.error('Failed to delete vaccine schedule:', err);
    }
  };

  const addMedicalRecord = async (record: Omit<MedicalRecord, 'id'>) => {
    const id = `mr-${Date.now()}`;
    const newRecord = {
      id,
      date: record.date,
      batch_id: record.batchId,
      disease: record.disease,
      medicine: record.medicine,
      dosage: record.dosage,
      cost: record.cost
    };

    const operations: any[] = [supabase.from('medical_records').insert(newRecord)];

    if (record.cost > 0) {
      const newExpense = {
        id: `exp-${Date.now()}`,
        category: 'Medicine',
        date: record.date,
        description: `Medical Treatment: Batch ${record.batchId} treated for ${record.disease} (${record.medicine})`,
        amount: record.cost,
        is_auto_generated: true,
        reference_id: id
      };
      operations.push(supabase.from('expenses').insert(newExpense));
    }

    await Promise.all(operations);
  };

  // 4. Egg Production
  const addEggCollection = async (collection: EggCollection) => {
    const newCollection = {
      date: collection.date,
      collected_qty: collection.collectedQty,
      damaged_qty: collection.damagedQty,
      net_qty: collection.netQty
    };
    await supabase.from('egg_collections').upsert(newCollection);
  };

  const deleteEggCollection = async (date: string) => {
    try {
      await supabase.from('egg_collections').delete().eq('date', date);
    } catch (err) {
      console.error('Failed to delete egg collection:', err);
    }
  };

  const addEggSale = async (sale: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => {
    const saleId = `s-${Date.now()}`;
    const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
    const newSale = {
      id: saleId,
      invoice_id: invoiceNum,
      type: 'Egg',
      date: sale.date,
      customer_name: sale.customerName,
      customer_contact: sale.customerContact,
      quantity: sale.quantity,
      unit_price: sale.unitPrice,
      total_amount: sale.totalAmount,
      details: sale.details
    };
    await supabase.from('sales').insert(newSale);
  };

  const deleteSale = async (saleId: string) => {
    try {
      const sale = sales.find(s => s.id === saleId);
      if (!sale) return;

      const operations: any[] = [supabase.from('sales').delete().eq('id', saleId)];

      if (sale.type === 'Bird' && sale.batchId) {
        const { data: batch } = await supabase
          .from('batches')
          .select('current_quantity')
          .eq('id', sale.batchId)
          .single();

        if (batch) {
          const newQty = batch.current_quantity + sale.quantity;
          operations.push(
            supabase
              .from('batches')
              .update({ current_quantity: newQty, status: 'Active' })
              .eq('id', sale.batchId)
          );
        }
      }

      await Promise.all(operations);
    } catch (err) {
      console.error('Failed to delete sale:', err);
    }
  };

  // 5. Expense Management
  const addExpense = async (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => {
    const newExpense = {
      id: `exp-${Date.now()}`,
      category: expense.category,
      date: expense.date,
      description: expense.description,
      amount: expense.amount,
      is_auto_generated: false
    };
    await supabase.from('expenses').insert(newExpense);
  };

  const deleteExpense = async (id: string) => {
    try {
      const { data: expense } = await supabase
        .from('expenses')
        .select('*')
        .eq('id', id)
        .single();

      if (!expense) return;

      await supabase.from('expenses').delete().eq('id', id);

      if (expense.is_auto_generated && expense.reference_id) {
        if (expense.category === 'Feed') {
          await supabase.from('feed_purchases').delete().eq('id', expense.reference_id);
        } else if (expense.category === 'Medicine') {
          await supabase.from('medical_records').delete().eq('id', expense.reference_id);
        }
      }
    } catch (err) {
      console.error('Failed to delete expense:', err);
    }
  };

  const updateBatch = async (batchId: string, updated: Omit<BirdBatch, 'id' | 'mortalityLogs'>) => {
    try {
      const cost = updated.type === 'Broiler' && updated.initialQuantityKg && updated.purchasePricePerKg
        ? updated.initialQuantityKg * updated.purchasePricePerKg
        : updated.initialQuantity * updated.purchasePrice;

      const updatedBatch: any = {
        type: updated.type,
        arrival_date: updated.arrivalDate,
        initial_quantity: updated.initialQuantity,
        current_quantity: updated.currentQuantity,
        purchase_price: updated.purchasePrice,
        status: updated.status,
        initial_quantity_kg: updated.type === 'Broiler' ? updated.initialQuantityKg : null,
        purchase_price_per_kg: updated.type === 'Broiler' ? updated.purchasePricePerKg : null
      };

      const { error: batchErr } = await supabase
        .from('batches')
        .update(updatedBatch)
        .eq('id', batchId);

      if (batchErr) {
        if (batchErr.code === 'PGRST204' || batchErr.message?.includes('initial_quantity_kg') || batchErr.message?.includes('schema cache')) {
          console.warn("Supabase schema cache missing initial_quantity_kg columns. Retrying batch update without them.");
          alert("Notice: Broiler weight-based columns do not exist in your Supabase database. The batch will be updated as a standard bird batch. Please run the SQL migration at the bottom of schema.sql in your Supabase SQL Editor.");
          
          delete updatedBatch.initial_quantity_kg;
          delete updatedBatch.purchase_price_per_kg;

          const { error: retryErr } = await supabase
            .from('batches')
            .update(updatedBatch)
            .eq('id', batchId);
          if (retryErr) throw retryErr;
        } else {
          throw batchErr;
        }
      }

      const { error: expErr } = await supabase
        .from('expenses')
        .update({
          date: updated.arrivalDate,
          description: `Bird Batch Purchase: ${updated.type} - ${updated.initialQuantity} birds (ID: ${batchId})`,
          amount: cost
        })
        .eq('reference_id', batchId)
        .eq('is_auto_generated', true);
      
      if (expErr) throw expErr;

      fetchAllData();
    } catch (err: any) {
      console.error('Failed to update batch:', err);
      alert(`Error updating batch: ${err.message || err}`);
    }
  };

  const updateFeedPurchase = async (purchaseId: string, updated: Omit<FeedPurchase, 'id'>) => {
    try {
      const updatedPurchase = {
        date: updated.date,
        feed_type: updated.feedType,
        quantity_kg: updated.quantityKg,
        cost: updated.cost,
        vendor: updated.vendor
      };
      await Promise.all([
        supabase.from('feed_purchases').update(updatedPurchase).eq('id', purchaseId),
        supabase
          .from('expenses')
          .update({
            date: updated.date,
            description: `Feed Purchase: ${updated.feedType} (${updated.quantityKg} kg) from ${updated.vendor}`,
            amount: updated.cost
          })
          .eq('reference_id', purchaseId)
          .eq('is_auto_generated', true)
      ]);
    } catch (err) {
      console.error('Failed to update feed purchase:', err);
    }
  };

  const updateFeedConsumption = async (consumptionId: string, updated: Omit<FeedConsumption, 'id'>) => {
    try {
      await supabase
        .from('feed_consumptions')
        .update({
          date: updated.date,
          feed_type: updated.feedType,
          batch_id: updated.batchId,
          quantity_kg: updated.quantityKg
        })
        .eq('id', consumptionId);
    } catch (err) {
      console.error('Failed to update feed consumption:', err);
    }
  };

  const updateVaccineSchedule = async (id: string, updated: Omit<VaccineSchedule, 'id'>) => {
    try {
      await supabase
        .from('vaccine_schedules')
        .update({
          vaccine_name: updated.vaccineName,
          batch_id: updated.batchId,
          scheduled_date: updated.scheduledDate,
          status: updated.status
         })
        .eq('id', id);
    } catch (err) {
      console.error('Failed to update vaccine schedule:', err);
    }
  };

  const updateMedicalRecord = async (recordId: string, updated: Omit<MedicalRecord, 'id'>) => {
    try {
      const updatedRecord = {
        date: updated.date,
        batch_id: updated.batchId,
        disease: updated.disease,
        medicine: updated.medicine,
        dosage: updated.dosage,
        cost: updated.cost
      };
      
      await supabase.from('medical_records').update(updatedRecord).eq('id', recordId);
      
      if (updated.cost > 0) {
        const newExpense = {
          category: 'Medicine',
          date: updated.date,
          description: `Medical Treatment: Batch ${updated.batchId} treated for ${updated.disease} (${updated.medicine})`,
          amount: updated.cost,
          is_auto_generated: true,
          reference_id: recordId
        };
        
        const { data: existingExp } = await supabase
          .from('expenses')
          .select('id')
          .eq('reference_id', recordId)
          .eq('is_auto_generated', true)
          .maybeSingle();
          
        if (existingExp) {
          await supabase
            .from('expenses')
            .update(newExpense)
            .eq('id', existingExp.id);
        } else {
          await supabase
            .from('expenses')
            .insert({
              id: `exp-${Date.now()}`,
              ...newExpense
            });
        }
      } else {
        await supabase
          .from('expenses')
          .delete()
          .eq('reference_id', recordId)
          .eq('is_auto_generated', true);
      }
    } catch (err) {
      console.error('Failed to update medical record:', err);
    }
  };

  const updateEggCollection = async (originalDate: string, updated: EggCollection) => {
    try {
      if (originalDate !== updated.date) {
        await supabase.from('egg_collections').delete().eq('date', originalDate);
      }
      await supabase.from('egg_collections').upsert({
        date: updated.date,
        collected_qty: updated.collectedQty,
        damaged_qty: updated.damagedQty,
        net_qty: updated.netQty
      });
    } catch (err) {
      console.error('Failed to update egg collection:', err);
    }
  };

  const updateSale = async (saleId: string, updated: Omit<Sale, 'id' | 'invoiceId'>) => {
    try {
      const sale = sales.find(s => s.id === saleId);
      if (!sale) return;
      
      const operations: any[] = [];
      
      if (sale.type === 'Bird' && sale.batchId) {
        const { data: oldBatch } = await supabase
          .from('batches')
          .select('current_quantity')
          .eq('id', sale.batchId)
          .single();
          
        if (oldBatch) {
          const revertedQty = oldBatch.current_quantity + sale.quantity;
          
          if (updated.type === 'Bird' && updated.batchId) {
            if (updated.batchId === sale.batchId) {
              const finalQty = revertedQty - updated.quantity;
              operations.push(
                supabase.from('batches').update({
                  current_quantity: Math.max(0, finalQty),
                  status: finalQty <= 0 ? 'Sold' : 'Active'
                }).eq('id', sale.batchId)
              );
            } else {
              operations.push(
                supabase.from('batches').update({
                  current_quantity: revertedQty,
                  status: revertedQty <= 0 ? 'Sold' : 'Active'
                }).eq('id', sale.batchId)
              );
              
              const { data: newBatch } = await supabase
                .from('batches')
                .select('current_quantity')
                .eq('id', updated.batchId)
                .single();
                
              if (newBatch) {
                const finalNewQty = Math.max(0, newBatch.current_quantity - updated.quantity);
                operations.push(
                  supabase.from('batches').update({
                    current_quantity: finalNewQty,
                    status: finalNewQty <= 0 ? 'Sold' : 'Active'
                  }).eq('id', updated.batchId)
                );
              }
            }
          } else {
            operations.push(
              supabase.from('batches').update({
                current_quantity: revertedQty,
                status: revertedQty <= 0 ? 'Sold' : 'Active'
              }).eq('id', sale.batchId)
            );
          }
        }
      } else if (updated.type === 'Bird' && updated.batchId) {
        const { data: newBatch } = await supabase
          .from('batches')
          .select('current_quantity')
          .eq('id', updated.batchId)
          .single();
          
        if (newBatch) {
          const finalNewQty = Math.max(0, newBatch.current_quantity - updated.quantity);
          operations.push(
            supabase.from('batches').update({
              current_quantity: finalNewQty,
              status: finalNewQty <= 0 ? 'Sold' : 'Active'
            }).eq('id', updated.batchId)
          );
        }
      }
      
      const updatedSale = {
        type: updated.type,
        date: updated.date,
        customer_name: updated.customerName,
        customer_contact: updated.customerContact,
        quantity: updated.quantity,
        unit_price: updated.unitPrice,
        total_amount: updated.totalAmount,
        batch_id: updated.batchId || null,
        details: updated.details || null
      };
      
      operations.push(
        supabase.from('sales').update(updatedSale).eq('id', saleId)
      );
      
      await Promise.all(operations);
    } catch (err) {
      console.error('Failed to update sale:', err);
    }
  };

  const updateExpense = async (id: string, updated: Omit<Expense, 'id' | 'isAutoGenerated'>) => {
    try {
      const expense = expenses.find(e => e.id === id);
      if (!expense) return;
      
      await supabase
        .from('expenses')
        .update({
          category: updated.category,
          date: updated.date,
          description: updated.description,
          amount: updated.amount
        })
        .eq('id', id);
        
      if (expense.isAutoGenerated && expense.referenceId) {
        if (expense.category === 'Feed') {
          await supabase
            .from('feed_purchases')
            .update({
              date: updated.date,
              cost: updated.amount
             })
            .eq('id', expense.referenceId);
        } else if (expense.category === 'Medicine') {
          await supabase
            .from('medical_records')
            .update({
              date: updated.date,
              cost: updated.amount
            })
            .eq('id', expense.referenceId);
        }
      }
    } catch (err) {
      console.error('Failed to update expense:', err);
    }
  };

  return (
    <FarmContext.Provider
      value={{
        currentUser,
        login,
        logout,
        batches,
        addBatch,
        deleteBatch,
        sellBatch,
        logMortality,
        feedPurchases,
        addFeedPurchase,
        feedConsumption,
        addFeedConsumption,
        vaccines,
        addVaccineSchedule,
        updateVaccineStatus,
        deleteVaccineSchedule,
        medicalRecords,
        addMedicalRecord,
        eggCollections,
        addEggCollection,
        deleteEggCollection,
        sales,
        addEggSale,
        deleteSale,
        expenses,
        addExpense,
        deleteExpense,
        updateBatch,
        updateFeedPurchase,
        updateFeedConsumption,
        updateVaccineSchedule,
        updateMedicalRecord,
        updateEggCollection,
        updateSale,
        updateExpense,
        getFeedStock,
        isLoading
      }}
    >
      {children}
    </FarmContext.Provider>
  );
};

export const useFarm = () => {
  const context = useContext(FarmContext);
  if (!context) {
    throw new Error('useFarm must be used within a FarmProvider');
  }
  return context;
};

